/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/v1/comparisons/{comparison_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Comparison */
        get: operations["getComparison"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/papers": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Papers */
        get: operations["listPapers"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/papers/{paper_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Paper */
        get: operations["getPaper"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/papers/{paper_id}/analysis": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Paper Analysis */
        get: operations["getPaperAnalysis"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/papers/{paper_id}/evidence": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Paper Evidence */
        get: operations["listPaperEvidence"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/papers/{paper_id}/related": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Paper Related Work */
        get: operations["getPaperRelatedWork"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/runs": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Runs */
        get: operations["listRuns"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/runs/latest": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Latest Run */
        get: operations["getLatestRun"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/topics": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Topics */
        get: operations["listTopics"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/health/live": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Liveness */
        get: operations["getLiveness"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/health/ready": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Readiness */
        get: operations["getReadiness"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** AnalysisClaimResponse */
        AnalysisClaimResponse: {
            /**
             * Analysis Id
             * Format: uuid
             */
            analysis_id: string;
            claim_type: components["schemas"]["ClaimType"];
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /**
             * Generated At
             * Format: date-time
             */
            generated_at: string;
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Key */
            key: string;
            /** Model Version */
            model_version: string;
            /**
             * Paper Id
             * Format: uuid
             */
            paper_id: string;
            /**
             * Paper Version Id
             * Format: uuid
             */
            paper_version_id: string;
            /** Prompt Version */
            prompt_version: string;
            /** Provider */
            provider: string;
            /** Schema Version */
            schema_version: number;
            /** Source */
            source: string;
            /** Text */
            text: string;
            verification_status: components["schemas"]["VerificationStatus"];
        };
        /**
         * AnalysisScope
         * @enum {string}
         */
        AnalysisScope: "ABSTRACT_ONLY" | "FULL_TEXT";
        /** ApiErrorDetail */
        ApiErrorDetail: {
            /** Code */
            code: string;
            /** Message */
            message: string;
        };
        /** ApiErrorResponse */
        ApiErrorResponse: {
            detail: components["schemas"]["ApiErrorDetail"];
        };
        /** CandidateDiscoveryResponse */
        CandidateDiscoveryResponse: {
            /** Action Id */
            action_id: string | null;
            /**
             * Candidate Id
             * Format: uuid
             */
            candidate_id: string;
            /**
             * Discovered At
             * Format: date-time
             */
            discovered_at: string;
            /**
             * Id
             * Format: uuid
             */
            id: string;
            origin: components["schemas"]["CandidateOrigin"];
            /** Relation Depth */
            relation_depth: number;
        };
        /**
         * CandidateOrigin
         * @enum {string}
         */
        CandidateOrigin: "SEARCH" | "REFERENCES" | "CITATIONS" | "RECOMMENDATIONS" | "LOCAL_LEXICAL" | "LOCAL_VECTOR";
        /** CandidateScoreComponentsResponse */
        CandidateScoreComponentsResponse: {
            /** Citation */
            citation: number;
            /** Entity Overlap */
            entity_overlap: number;
            /** Final */
            final: number;
            /** Lexical */
            lexical: number;
            /** Recommendation */
            recommendation: number;
            /** Semantic Scholar */
            semantic_scholar: number;
            /** Vector */
            vector: number;
        };
        /**
         * ClaimType
         * @enum {string}
         */
        ClaimType: "RESEARCH_PROBLEM" | "METHOD" | "CONTRIBUTION" | "RESULT" | "LIMITATION";
        /**
         * ComparabilityStatus
         * @enum {string}
         */
        ComparabilityStatus: "DIRECTLY_COMPARABLE" | "PARTIALLY_COMPARABLE" | "NOT_DIRECTLY_COMPARABLE" | "INSUFFICIENT_EVIDENCE";
        /**
         * ComparisonDimensionName
         * @enum {string}
         */
        ComparisonDimensionName: "RESEARCH_PROBLEM" | "TASK" | "METHOD" | "ARCHITECTURE" | "DATASETS" | "BENCHMARKS" | "BASELINES" | "METRICS" | "REPORTED_RESULTS" | "COMPUTE_OR_INFERENCE_BUDGET" | "CLAIMED_NOVELTY" | "LIMITATIONS" | "CODE_AVAILABILITY" | "RESULT_COMPARABILITY";
        /** ComparisonDimensionResponse */
        ComparisonDimensionResponse: {
            /** Assessment */
            assessment: string;
            /**
             * Comparison Id
             * Format: uuid
             */
            comparison_id: string;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /**
             * Id
             * Format: uuid
             */
            id: string;
            name: components["schemas"]["ComparisonDimensionName"];
            /** Position */
            position: number;
            /** Schema Version */
            schema_version: number;
            /** Source Evidence Ids */
            source_evidence_ids: string[];
            /** Source Value */
            source_value: string;
            /** Target Evidence Ids */
            target_evidence_ids: string[];
            /** Target Value */
            target_value: string;
        };
        /** ComparisonEvidenceResponse */
        ComparisonEvidenceResponse: {
            /**
             * Analysis Id
             * Format: uuid
             */
            analysis_id: string;
            analysis_scope: components["schemas"]["AnalysisScope"];
            evidence_type: components["schemas"]["EvidenceType"];
            /** Excerpt */
            excerpt: string;
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /**
             * Paper Id
             * Format: uuid
             */
            paper_id: string;
            /**
             * Paper Version Id
             * Format: uuid
             */
            paper_version_id: string;
            /** Section */
            section: string;
            verification_status: components["schemas"]["VerificationStatus"];
        };
        /** ComparisonResponse */
        ComparisonResponse: {
            /** Comparability Reason */
            comparability_reason: string;
            comparability_status: components["schemas"]["ComparabilityStatus"];
            /** Configured Model */
            configured_model: string;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /** Dimensions */
            dimensions: components["schemas"]["ComparisonDimensionResponse"][];
            /** Evidence */
            evidence: components["schemas"]["ComparisonEvidenceResponse"][];
            /**
             * Generated At
             * Format: date-time
             */
            generated_at: string;
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Model Version */
            model_version: string;
            /** Prompt Version */
            prompt_version: string;
            /** Provider */
            provider: string;
            /** Relations */
            relations: components["schemas"]["PaperRelationResponse"][];
            /** Schema Version */
            schema_version: number;
            /**
             * Search Session Id
             * Format: uuid
             */
            search_session_id: string;
            /** Source */
            source: string;
            /**
             * Source Analysis Id
             * Format: uuid
             */
            source_analysis_id: string;
            source_analysis_scope: components["schemas"]["AnalysisScope"];
            /**
             * Source Paper Id
             * Format: uuid
             */
            source_paper_id: string;
            /**
             * Source Paper Version Id
             * Format: uuid
             */
            source_paper_version_id: string;
            /** Summary */
            summary: string;
            /**
             * Target Analysis Id
             * Format: uuid
             */
            target_analysis_id: string;
            target_analysis_scope: components["schemas"]["AnalysisScope"];
            /**
             * Target Paper Id
             * Format: uuid
             */
            target_paper_id: string;
            /**
             * Target Paper Version Id
             * Format: uuid
             */
            target_paper_version_id: string;
            usage: components["schemas"]["ModelUsageResponse"];
            verification_status: components["schemas"]["VerificationStatus"];
        };
        /** EvidenceListResponse */
        EvidenceListResponse: {
            /** Items */
            items: components["schemas"]["EvidenceResponse"][];
            /** Total */
            total: number;
        };
        /** EvidenceResponse */
        EvidenceResponse: {
            /**
             * Analysis Id
             * Format: uuid
             */
            analysis_id: string;
            /** Coordinates */
            coordinates: components["schemas"]["PageCoordinatesResponse"][];
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            evidence_type: components["schemas"]["EvidenceType"];
            /** Excerpt */
            excerpt: string;
            /** Extraction Source */
            extraction_source: string;
            /**
             * Generated At
             * Format: date-time
             */
            generated_at: string;
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Key */
            key: string;
            /** Model Version */
            model_version: string;
            /**
             * Paper Id
             * Format: uuid
             */
            paper_id: string;
            /**
             * Paper Version Id
             * Format: uuid
             */
            paper_version_id: string;
            /** Passage Id */
            passage_id: string;
            /** Prompt Version */
            prompt_version: string;
            /** Provider */
            provider: string;
            /** Schema Version */
            schema_version: number;
            /** Section */
            section: string;
            /** Supported Claim Ids */
            supported_claim_ids: string[];
            verification_status: components["schemas"]["VerificationStatus"];
        };
        /**
         * EvidenceType
         * @enum {string}
         */
        EvidenceType: "SUPPORTS" | "QUALIFIES" | "CONTRADICTS";
        /** ExternalPaperResponse */
        ExternalPaperResponse: {
            /** Abstract */
            abstract: string | null;
            /** Arxiv Id */
            arxiv_id: string | null;
            /** Authors */
            authors: string[];
            /** Citation Count */
            citation_count: number;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /** Doi */
            doi: string | null;
            /** External Ids */
            external_ids: {
                [key: string]: string;
            };
            /** Full Text Available */
            full_text_available: boolean;
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Influential Citation Count */
            influential_citation_count: number;
            /** Publication Date */
            publication_date: string | null;
            /** Schema Version */
            schema_version: number;
            /** Semantic Scholar Id */
            semantic_scholar_id: string;
            /**
             * Source
             * @constant
             */
            source: "semantic_scholar";
            /** Title */
            title: string;
            /**
             * Updated At
             * Format: date-time
             */
            updated_at: string;
            /** Venue */
            venue: string | null;
            /** Year */
            year: number | null;
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /** LiveResponse */
        LiveResponse: {
            /**
             * Status
             * @default alive
             * @constant
             */
            status: "alive";
        };
        /** ModelUsageResponse */
        ModelUsageResponse: {
            /** Call Count */
            call_count: number;
            /** Completion Tokens */
            completion_tokens: number;
            /** Duration Ms */
            duration_ms: number;
            /** Estimated Cost Usd */
            estimated_cost_usd: string | null;
            /** Prompt Tokens */
            prompt_tokens: number;
            /** Total Tokens */
            total_tokens: number;
        };
        /** PageCoordinatesResponse */
        PageCoordinatesResponse: {
            /** Height */
            height: number;
            /** Page */
            page: number;
            /** Width */
            width: number;
            /** X */
            x: number;
            /** Y */
            y: number;
        };
        /** PaperAnalysisResponse */
        PaperAnalysisResponse: {
            analysis_scope: components["schemas"]["AnalysisScope"];
            /** Arxiv Version */
            arxiv_version: number;
            /** Claims */
            claims: components["schemas"]["AnalysisClaimResponse"][];
            /** Configured Model */
            configured_model: string;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /**
             * Generated At
             * Format: date-time
             */
            generated_at: string;
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Key Contributions */
            key_contributions: string[];
            /** Limitations */
            limitations: string[];
            /** Method Summary */
            method_summary: string;
            /** Model Version */
            model_version: string;
            /**
             * Paper Id
             * Format: uuid
             */
            paper_id: string;
            /**
             * Paper Version Id
             * Format: uuid
             */
            paper_version_id: string;
            /** Parsed Paper Id */
            parsed_paper_id: string | null;
            /** Parser Name */
            parser_name: string | null;
            /** Parser Version */
            parser_version: string | null;
            /** Prompt Version */
            prompt_version: string;
            /** Provider */
            provider: string;
            /** Research Problem */
            research_problem: string;
            /** Schema Version */
            schema_version: number;
            /** Source */
            source: string;
            /** Summary */
            summary: string;
            usage: components["schemas"]["ModelUsageResponse"];
            verification_status: components["schemas"]["VerificationStatus"];
        };
        /** PaperDetailResponse */
        PaperDetailResponse: {
            /** Abstract */
            abstract: string;
            /** Authors */
            authors: string[];
            /** Canonical Arxiv Id */
            canonical_arxiv_id: string;
            /** Categories */
            categories: string[];
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /** Current Version */
            current_version: number;
            /**
             * First Submitted At
             * Format: date-time
             */
            first_submitted_at: string;
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /**
             * Latest Updated At
             * Format: date-time
             */
            latest_updated_at: string;
            /** Pdf Url */
            pdf_url: string;
            /** Primary Category */
            primary_category: string;
            /** Schema Version */
            schema_version: number;
            /** Source Identities */
            source_identities: components["schemas"]["SourceIdentityResponse"][];
            /** Title */
            title: string;
            /** Topic Slugs */
            topic_slugs: string[];
            /** Versions */
            versions: components["schemas"]["PaperVersionResponse"][];
        };
        /** PaperListResponse */
        PaperListResponse: {
            /** Items */
            items: components["schemas"]["PaperSummary"][];
            /** Limit */
            limit: number;
            /** Offset */
            offset: number;
            /** Total */
            total: number;
        };
        /** PaperRelationResponse */
        PaperRelationResponse: {
            /** Confidence */
            confidence: number | null;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /** Evidence Ids */
            evidence_ids: string[];
            /**
             * Generated At
             * Format: date-time
             */
            generated_at: string;
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Justification */
            justification: string;
            /** Model Version */
            model_version: string | null;
            /** Prompt Version */
            prompt_version: string | null;
            provenance: components["schemas"]["RelationProvenance"];
            /** Provider */
            provider: string | null;
            relation_type: components["schemas"]["PaperRelationType"];
            /** Schema Version */
            schema_version: number;
            /**
             * Source Paper Id
             * Format: uuid
             */
            source_paper_id: string;
            /**
             * Source Paper Version Id
             * Format: uuid
             */
            source_paper_version_id: string;
            /**
             * Target Paper Id
             * Format: uuid
             */
            target_paper_id: string;
            /**
             * Target Paper Version Id
             * Format: uuid
             */
            target_paper_version_id: string;
            verification_status: components["schemas"]["VerificationStatus"];
        };
        /**
         * PaperRelationType
         * @enum {string}
         */
        PaperRelationType: "CITES" | "SIMILAR_TO" | "EXTENDS" | "COMPARES_WITH" | "CONTRADICTS" | "IMPROVES_ON";
        /**
         * PaperStage
         * @enum {string}
         */
        PaperStage: "DISCOVERED" | "NORMALIZED" | "ENRICHED" | "RELEVANCE_SCORED" | "SELECTED" | "PDF_DOWNLOADED" | "PARSED" | "ANALYZED" | "EVIDENCE_EXTRACTED" | "PRIOR_WORK_RETRIEVED" | "COMPARED" | "GRAPH_UPDATED" | "PUBLISHED";
        /** PaperSummary */
        PaperSummary: {
            /** Abstract */
            abstract: string;
            /** Authors */
            authors: string[];
            /** Canonical Arxiv Id */
            canonical_arxiv_id: string;
            /** Categories */
            categories: string[];
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /** Current Version */
            current_version: number;
            /**
             * First Submitted At
             * Format: date-time
             */
            first_submitted_at: string;
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /**
             * Latest Updated At
             * Format: date-time
             */
            latest_updated_at: string;
            /** Pdf Url */
            pdf_url: string;
            /** Primary Category */
            primary_category: string;
            /** Schema Version */
            schema_version: number;
            /** Title */
            title: string;
        };
        /** PaperVersionResponse */
        PaperVersionResponse: {
            /** Abstract */
            abstract: string;
            /** Authors */
            authors: string[];
            /** Canonical Arxiv Id */
            canonical_arxiv_id: string;
            /** Categories */
            categories: string[];
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /**
             * Paper Id
             * Format: uuid
             */
            paper_id: string;
            /** Pdf Url */
            pdf_url: string;
            /** Primary Category */
            primary_category: string;
            /** Schema Version */
            schema_version: number;
            /** Source Url */
            source_url: string;
            /**
             * Submitted At
             * Format: date-time
             */
            submitted_at: string;
            /** Title */
            title: string;
            /**
             * Updated At
             * Format: date-time
             */
            updated_at: string;
            /** Version */
            version: number;
        };
        /** ReadyResponse */
        ReadyResponse: {
            /**
             * Database
             * @default ready
             * @constant
             */
            database: "ready";
            /**
             * Migrations
             * @default current
             * @constant
             */
            migrations: "current";
            /**
             * Status
             * @default ready
             * @constant
             */
            status: "ready";
        };
        /** RelatedComparisonSummaryResponse */
        RelatedComparisonSummaryResponse: {
            comparability_status: components["schemas"]["ComparabilityStatus"];
            /**
             * Generated At
             * Format: date-time
             */
            generated_at: string;
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Model Version */
            model_version: string;
            /** Prompt Version */
            prompt_version: string;
            /** Provider */
            provider: string;
            /** Summary */
            summary: string;
            /**
             * Target Analysis Id
             * Format: uuid
             */
            target_analysis_id: string;
            target_analysis_scope: components["schemas"]["AnalysisScope"];
            /**
             * Target Paper Id
             * Format: uuid
             */
            target_paper_id: string;
            /**
             * Target Paper Version Id
             * Format: uuid
             */
            target_paper_version_id: string;
            verification_status: components["schemas"]["VerificationStatus"];
        };
        /** RelatedWorkItemResponse */
        RelatedWorkItemResponse: {
            candidate: components["schemas"]["SearchCandidateResponse"];
            /** Comparison Id */
            comparison_id: string | null;
            /** Discoveries */
            discoveries: components["schemas"]["CandidateDiscoveryResponse"][];
            paper: components["schemas"]["ExternalPaperResponse"];
            /** Relations */
            relations: components["schemas"]["PaperRelationResponse"][];
        };
        /** RelatedWorkResponse */
        RelatedWorkResponse: {
            /** Actions */
            actions: components["schemas"]["SearchActionResponse"][];
            /** Comparisons */
            comparisons: components["schemas"]["RelatedComparisonSummaryResponse"][];
            /** Items */
            items: components["schemas"]["RelatedWorkItemResponse"][];
            /**
             * Paper Id
             * Format: uuid
             */
            paper_id: string;
            session: components["schemas"]["SearchSessionResponse"] | null;
            /** Total */
            total: number;
        };
        /**
         * RelationProvenance
         * @enum {string}
         */
        RelationProvenance: "METADATA_EXPLICIT" | "TEXT_EXPLICIT" | "DETERMINISTICALLY_DERIVED" | "LLM_INFERRED" | "HUMAN_VERIFIED";
        /** ReportFailureResponse */
        ReportFailureResponse: {
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /** Error Code */
            error_code: string;
            /** Error Detail */
            error_detail: string;
            failed_stage: components["schemas"]["PaperStage"];
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /**
             * Paper Id
             * Format: uuid
             */
            paper_id: string;
            /**
             * Paper Version Id
             * Format: uuid
             */
            paper_version_id: string;
            /**
             * Report Id
             * Format: uuid
             */
            report_id: string;
            /** Retryable */
            retryable: boolean;
            /** Schema Version */
            schema_version: number;
        };
        /** ReportResponse */
        ReportResponse: {
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /** Failures */
            failures: components["schemas"]["ReportFailureResponse"][];
            /**
             * Generated At
             * Format: date-time
             */
            generated_at: string;
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /**
             * Logical Date
             * Format: date
             */
            logical_date: string;
            /**
             * Run Id
             * Format: uuid
             */
            run_id: string;
            /** Schema Version */
            schema_version: number;
            /** Source */
            source: string;
            status: components["schemas"]["RunStatus"];
            /** Summary */
            summary: string;
            /** Title */
            title: string;
            /**
             * Topic Id
             * Format: uuid
             */
            topic_id: string;
        };
        /** RunDetailResponse */
        RunDetailResponse: {
            analysis_scope: components["schemas"]["AnalysisScope"] | null;
            /** Completed At */
            completed_at: string | null;
            /** Completed Count */
            completed_count: number;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /** Cursor From */
            cursor_from: string | null;
            /** Cursor To */
            cursor_to: string | null;
            /** Discovered Count */
            discovered_count: number;
            /** Error Code */
            error_code: string | null;
            /** Error Detail */
            error_detail: string | null;
            /** Failed Count */
            failed_count: number;
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Items */
            items: components["schemas"]["RunItemResponse"][];
            /**
             * Logical Date
             * Format: date
             */
            logical_date: string;
            /** Normalized Count */
            normalized_count: number;
            operation: components["schemas"]["RunOperation"];
            report: components["schemas"]["ReportResponse"] | null;
            /** Schema Version */
            schema_version: number;
            /** Selected Count */
            selected_count: number;
            /**
             * Started At
             * Format: date-time
             */
            started_at: string;
            status: components["schemas"]["RunStatus"];
            /**
             * Topic Id
             * Format: uuid
             */
            topic_id: string;
        };
        /** RunItemResponse */
        RunItemResponse: {
            /** Canonical Arxiv Id */
            canonical_arxiv_id: string;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /** Error Code */
            error_code: string | null;
            /** Error Detail */
            error_detail: string | null;
            failed_stage: components["schemas"]["PaperStage"] | null;
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /**
             * Paper Id
             * Format: uuid
             */
            paper_id: string;
            /** Paper Title */
            paper_title: string;
            /**
             * Paper Version Id
             * Format: uuid
             */
            paper_version_id: string;
            /** Retryable */
            retryable: boolean | null;
            /**
             * Run Id
             * Format: uuid
             */
            run_id: string;
            /** Schema Version */
            schema_version: number;
            stage: components["schemas"]["PaperStage"];
            status: components["schemas"]["RunItemStatus"];
            /**
             * Updated At
             * Format: date-time
             */
            updated_at: string;
        };
        /**
         * RunItemStatus
         * @enum {string}
         */
        RunItemStatus: "IN_PROGRESS" | "COMPLETED" | "FAILED";
        /** RunListResponse */
        RunListResponse: {
            /** Items */
            items: components["schemas"]["RunSummary"][];
            /** Limit */
            limit: number;
            /** Offset */
            offset: number;
            /** Total */
            total: number;
        };
        /**
         * RunOperation
         * @enum {string}
         */
        RunOperation: "ARXIV_INGESTION" | "STRUCTURED_ANALYSIS";
        /**
         * RunStatus
         * @enum {string}
         */
        RunStatus: "RUNNING" | "COMPLETE" | "PARTIAL" | "FAILED";
        /** RunSummary */
        RunSummary: {
            analysis_scope: components["schemas"]["AnalysisScope"] | null;
            /** Completed At */
            completed_at: string | null;
            /** Completed Count */
            completed_count: number;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /** Cursor From */
            cursor_from: string | null;
            /** Cursor To */
            cursor_to: string | null;
            /** Discovered Count */
            discovered_count: number;
            /** Error Code */
            error_code: string | null;
            /** Error Detail */
            error_detail: string | null;
            /** Failed Count */
            failed_count: number;
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /**
             * Logical Date
             * Format: date
             */
            logical_date: string;
            /** Normalized Count */
            normalized_count: number;
            operation: components["schemas"]["RunOperation"];
            /** Schema Version */
            schema_version: number;
            /** Selected Count */
            selected_count: number;
            /**
             * Started At
             * Format: date-time
             */
            started_at: string;
            status: components["schemas"]["RunStatus"];
            /**
             * Topic Id
             * Format: uuid
             */
            topic_id: string;
        };
        /** SearchActionResponse */
        SearchActionResponse: {
            /** Completed At */
            completed_at: string | null;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /** Decision Reason */
            decision_reason: string;
            /** Duration Ms */
            duration_ms: number;
            /** Error Code */
            error_code: string | null;
            /** Error Detail */
            error_detail: string | null;
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Positive Paper Ids */
            positive_paper_ids: string[];
            /** Query */
            query: string | null;
            /** Relation Depth */
            relation_depth: number;
            /** Requested Limit */
            requested_limit: number;
            /** Result Count */
            result_count: number;
            /** Retryable */
            retryable: boolean | null;
            /** Schema Version */
            schema_version: number;
            /**
             * Session Id
             * Format: uuid
             */
            session_id: string;
            status: components["schemas"]["SearchActionStatus"];
            /** Step */
            step: number;
            /** Target Arxiv Id */
            target_arxiv_id: string | null;
            /** Target Semantic Scholar Id */
            target_semantic_scholar_id: string | null;
            tool: components["schemas"]["SearchTool"];
            /** Year From */
            year_from: number | null;
            /** Year To */
            year_to: number | null;
        };
        /**
         * SearchActionStatus
         * @enum {string}
         */
        SearchActionStatus: "RUNNING" | "COMPLETED" | "FAILED";
        /** SearchCandidateResponse */
        SearchCandidateResponse: {
            /** Configured Model */
            configured_model: string | null;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            decision: components["schemas"]["SelectionDecision"];
            /** Decision Reason */
            decision_reason: string;
            /** Discovered By Action Id */
            discovered_by_action_id: string | null;
            /**
             * External Paper Id
             * Format: uuid
             */
            external_paper_id: string;
            /** Generated At */
            generated_at: string | null;
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Local Paper Id */
            local_paper_id: string | null;
            /** Local Paper Version Id */
            local_paper_version_id: string | null;
            /** Model Version */
            model_version: string | null;
            /** Origins */
            origins: components["schemas"]["CandidateOrigin"][];
            /** Prompt Version */
            prompt_version: string | null;
            /** Provider */
            provider: string | null;
            /** Rank */
            rank: number;
            /** Relation Depth */
            relation_depth: number;
            /** Schema Version */
            schema_version: number;
            scores: components["schemas"]["CandidateScoreComponentsResponse"];
            /** Semantic Scholar Id */
            semantic_scholar_id: string;
            /**
             * Session Id
             * Format: uuid
             */
            session_id: string;
            verification_status: components["schemas"]["VerificationStatus"];
        };
        /** SearchLimitsResponse */
        SearchLimitsResponse: {
            /** Max Candidates */
            max_candidates: number;
            /** Max Citation Depth */
            max_citation_depth: number;
            /** Max Queries */
            max_queries: number;
            /** Max Queue Size */
            max_queue_size: number;
            /** Max Selected Candidates */
            max_selected_candidates: number;
            /** Max Steps */
            max_steps: number;
            /** Overall Timeout Seconds */
            overall_timeout_seconds: number;
            /** Per Operation Timeout Seconds */
            per_operation_timeout_seconds: number;
        };
        /** SearchSessionResponse */
        SearchSessionResponse: {
            /** Completed At */
            completed_at: string | null;
            /** Configured Model */
            configured_model: string | null;
            /** Crawler Decision Reason */
            crawler_decision_reason: string | null;
            /** Crawler Expand Citations */
            crawler_expand_citations: boolean | null;
            /** Crawler Expand References */
            crawler_expand_references: boolean | null;
            /** Crawler Generated At */
            crawler_generated_at: string | null;
            /** Crawler Queries */
            crawler_queries: string[] | null;
            /** Crawler Use Recommendations */
            crawler_use_recommendations: boolean | null;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /** Effective Year To */
            effective_year_to: number;
            /** Error Code */
            error_code: string | null;
            /** Error Detail */
            error_detail: string | null;
            /**
             * Id
             * Format: uuid
             */
            id: string;
            limits: components["schemas"]["SearchLimitsResponse"];
            /** Model Version */
            model_version: string | null;
            /** Objective */
            objective: string;
            /** Prompt Version */
            prompt_version: string | null;
            /** Provider */
            provider: string | null;
            /** Requested Year From */
            requested_year_from: number;
            /** Schema Version */
            schema_version: number;
            /**
             * Source Analysis Id
             * Format: uuid
             */
            source_analysis_id: string;
            source_analysis_scope: components["schemas"]["AnalysisScope"];
            /**
             * Source Paper Id
             * Format: uuid
             */
            source_paper_id: string;
            /**
             * Source Paper Version Id
             * Format: uuid
             */
            source_paper_version_id: string;
            /**
             * Started At
             * Format: date-time
             */
            started_at: string;
            status: components["schemas"]["SearchSessionStatus"];
            stop_reason: components["schemas"]["SearchStopReason"] | null;
            /**
             * Topic Id
             * Format: uuid
             */
            topic_id: string;
            usage: components["schemas"]["ModelUsageResponse"] | null;
        };
        /**
         * SearchSessionStatus
         * @enum {string}
         */
        SearchSessionStatus: "RUNNING" | "COMPLETE" | "FAILED";
        /**
         * SearchStopReason
         * @enum {string}
         */
        SearchStopReason: "QUEUE_EXHAUSTED" | "MAX_STEPS" | "MAX_QUERIES" | "MAX_QUEUE_SIZE" | "MAX_CANDIDATES" | "MAX_SELECTED_CANDIDATES" | "OVERALL_TIMEOUT" | "FAILED";
        /**
         * SearchTool
         * @enum {string}
         */
        SearchTool: "search_papers" | "get_paper" | "get_references" | "get_citations" | "get_recommendations" | "read_arxiv_paper";
        /**
         * SelectionDecision
         * @enum {string}
         */
        SelectionDecision: "PENDING" | "SELECTED" | "REJECTED";
        /** SourceIdentityResponse */
        SourceIdentityResponse: {
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /** External Id */
            external_id: string;
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /**
             * Paper Id
             * Format: uuid
             */
            paper_id: string;
            /**
             * Paper Version Id
             * Format: uuid
             */
            paper_version_id: string;
            /** Schema Version */
            schema_version: number;
            /**
             * Source
             * @constant
             */
            source: "arxiv";
            /** Source Url */
            source_url: string;
            /** Source Version */
            source_version: string;
        };
        /** TopicListResponse */
        TopicListResponse: {
            /** Items */
            items: components["schemas"]["TopicSummary"][];
            /** Total */
            total: number;
        };
        /** TopicSummary */
        TopicSummary: {
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /** Description */
            description: string;
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Name */
            name: string;
            /** Schema Version */
            schema_version: number;
            /** Slug */
            slug: string;
        };
        /** ValidationError */
        ValidationError: {
            /** Context */
            ctx?: Record<string, never>;
            /** Input */
            input?: unknown;
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
        };
        /**
         * VerificationStatus
         * @enum {string}
         */
        VerificationStatus: "UNVERIFIED" | "HUMAN_VERIFIED" | "REJECTED";
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    getComparison: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                comparison_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ComparisonResponse"];
                };
            };
            /** @description Comparison not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiErrorResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
            /** @description Comparison storage unavailable */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiErrorResponse"];
                };
            };
        };
    };
    listPapers: {
        parameters: {
            query?: {
                topic?: string | null;
                limit?: number;
                offset?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PaperListResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    getPaper: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                paper_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PaperDetailResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    getPaperAnalysis: {
        parameters: {
            query?: {
                paper_version_id?: string | null;
                scope?: components["schemas"]["AnalysisScope"] | null;
            };
            header?: never;
            path: {
                paper_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PaperAnalysisResponse"];
                };
            };
            /** @description Paper or analysis not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiErrorResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
            /** @description Analysis storage unavailable */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiErrorResponse"];
                };
            };
        };
    };
    listPaperEvidence: {
        parameters: {
            query: {
                analysis_id: string;
                paper_version_id?: string | null;
                scope?: components["schemas"]["AnalysisScope"] | null;
            };
            header?: never;
            path: {
                paper_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EvidenceListResponse"];
                };
            };
            /** @description Paper or analysis not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiErrorResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
            /** @description Evidence storage unavailable */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiErrorResponse"];
                };
            };
        };
    };
    getPaperRelatedWork: {
        parameters: {
            query?: {
                paper_version_id?: string | null;
            };
            header?: never;
            path: {
                paper_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RelatedWorkResponse"];
                };
            };
            /** @description Paper not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiErrorResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
            /** @description Related-work storage unavailable */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiErrorResponse"];
                };
            };
        };
    };
    listRuns: {
        parameters: {
            query?: {
                topic?: string | null;
                limit?: number;
                offset?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RunListResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    getLatestRun: {
        parameters: {
            query?: {
                topic?: string | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RunDetailResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    listTopics: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TopicListResponse"];
                };
            };
        };
    };
    getLiveness: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["LiveResponse"];
                };
            };
        };
    };
    getReadiness: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ReadyResponse"];
                };
            };
            /** @description Database unavailable or migration incompatible */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
}
