/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/v1/papers": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Papers */
        get: operations["listPapers"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/papers/{paper_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Paper */
        get: operations["getPaper"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/runs": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Runs */
        get: operations["listRuns"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/runs/latest": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Latest Run */
        get: operations["getLatestRun"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/topics": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Topics */
        get: operations["listTopics"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/health/live": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Liveness */
        get: operations["getLiveness"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/health/ready": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Readiness */
        get: operations["getReadiness"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /** LiveResponse */
        LiveResponse: {
            /**
             * Status
             * @default alive
             * @constant
             */
            status: "alive";
        };
        /** PaperDetailResponse */
        PaperDetailResponse: {
            /** Abstract */
            abstract: string;
            /** Authors */
            authors: string[];
            /** Canonical Arxiv Id */
            canonical_arxiv_id: string;
            /** Categories */
            categories: string[];
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /** Current Version */
            current_version: number;
            /**
             * First Submitted At
             * Format: date-time
             */
            first_submitted_at: string;
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /**
             * Latest Updated At
             * Format: date-time
             */
            latest_updated_at: string;
            /** Pdf Url */
            pdf_url: string;
            /** Primary Category */
            primary_category: string;
            /** Schema Version */
            schema_version: number;
            /** Source Identities */
            source_identities: components["schemas"]["SourceIdentityResponse"][];
            /** Title */
            title: string;
            /** Topic Slugs */
            topic_slugs: string[];
            /** Versions */
            versions: components["schemas"]["PaperVersionResponse"][];
        };
        /** PaperListResponse */
        PaperListResponse: {
            /** Items */
            items: components["schemas"]["PaperSummary"][];
            /** Limit */
            limit: number;
            /** Offset */
            offset: number;
            /** Total */
            total: number;
        };
        /**
         * PaperStage
         * @enum {string}
         */
        PaperStage: "DISCOVERED" | "NORMALIZED" | "ENRICHED" | "RELEVANCE_SCORED" | "SELECTED" | "PDF_DOWNLOADED" | "PARSED" | "ANALYZED" | "EVIDENCE_EXTRACTED" | "PRIOR_WORK_RETRIEVED" | "COMPARED" | "GRAPH_UPDATED" | "PUBLISHED";
        /** PaperSummary */
        PaperSummary: {
            /** Abstract */
            abstract: string;
            /** Authors */
            authors: string[];
            /** Canonical Arxiv Id */
            canonical_arxiv_id: string;
            /** Categories */
            categories: string[];
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /** Current Version */
            current_version: number;
            /**
             * First Submitted At
             * Format: date-time
             */
            first_submitted_at: string;
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /**
             * Latest Updated At
             * Format: date-time
             */
            latest_updated_at: string;
            /** Pdf Url */
            pdf_url: string;
            /** Primary Category */
            primary_category: string;
            /** Schema Version */
            schema_version: number;
            /** Title */
            title: string;
        };
        /** PaperVersionResponse */
        PaperVersionResponse: {
            /** Abstract */
            abstract: string;
            /** Authors */
            authors: string[];
            /** Canonical Arxiv Id */
            canonical_arxiv_id: string;
            /** Categories */
            categories: string[];
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /**
             * Paper Id
             * Format: uuid
             */
            paper_id: string;
            /** Pdf Url */
            pdf_url: string;
            /** Primary Category */
            primary_category: string;
            /** Schema Version */
            schema_version: number;
            /** Source Url */
            source_url: string;
            /**
             * Submitted At
             * Format: date-time
             */
            submitted_at: string;
            /** Title */
            title: string;
            /**
             * Updated At
             * Format: date-time
             */
            updated_at: string;
            /** Version */
            version: number;
        };
        /** ReadyResponse */
        ReadyResponse: {
            /**
             * Database
             * @default ready
             * @constant
             */
            database: "ready";
            /**
             * Migrations
             * @default current
             * @constant
             */
            migrations: "current";
            /**
             * Status
             * @default ready
             * @constant
             */
            status: "ready";
        };
        /** RunDetailResponse */
        RunDetailResponse: {
            /** Completed At */
            completed_at: string | null;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /**
             * Cursor From
             * Format: date-time
             */
            cursor_from: string;
            /**
             * Cursor To
             * Format: date-time
             */
            cursor_to: string;
            /** Discovered Count */
            discovered_count: number;
            /** Error Code */
            error_code: string | null;
            /** Error Detail */
            error_detail: string | null;
            /** Failed Count */
            failed_count: number;
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Items */
            items: components["schemas"]["RunItemResponse"][];
            /**
             * Logical Date
             * Format: date
             */
            logical_date: string;
            /** Normalized Count */
            normalized_count: number;
            operation: components["schemas"]["RunOperation"];
            /** Schema Version */
            schema_version: number;
            /**
             * Started At
             * Format: date-time
             */
            started_at: string;
            status: components["schemas"]["RunStatus"];
            /**
             * Topic Id
             * Format: uuid
             */
            topic_id: string;
        };
        /** RunItemResponse */
        RunItemResponse: {
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /** Error Code */
            error_code: string | null;
            /** Error Detail */
            error_detail: string | null;
            failed_stage: components["schemas"]["PaperStage"] | null;
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /**
             * Paper Id
             * Format: uuid
             */
            paper_id: string;
            /**
             * Paper Version Id
             * Format: uuid
             */
            paper_version_id: string;
            /** Retryable */
            retryable: boolean | null;
            /**
             * Run Id
             * Format: uuid
             */
            run_id: string;
            /** Schema Version */
            schema_version: number;
            stage: components["schemas"]["PaperStage"];
            status: components["schemas"]["RunItemStatus"];
            /**
             * Updated At
             * Format: date-time
             */
            updated_at: string;
        };
        /**
         * RunItemStatus
         * @enum {string}
         */
        RunItemStatus: "IN_PROGRESS" | "COMPLETED" | "FAILED";
        /** RunListResponse */
        RunListResponse: {
            /** Items */
            items: components["schemas"]["RunSummary"][];
            /** Limit */
            limit: number;
            /** Offset */
            offset: number;
            /** Total */
            total: number;
        };
        /**
         * RunOperation
         * @enum {string}
         */
        RunOperation: "ARXIV_INGESTION";
        /**
         * RunStatus
         * @enum {string}
         */
        RunStatus: "RUNNING" | "COMPLETE" | "PARTIAL" | "FAILED";
        /** RunSummary */
        RunSummary: {
            /** Completed At */
            completed_at: string | null;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /**
             * Cursor From
             * Format: date-time
             */
            cursor_from: string;
            /**
             * Cursor To
             * Format: date-time
             */
            cursor_to: string;
            /** Discovered Count */
            discovered_count: number;
            /** Error Code */
            error_code: string | null;
            /** Error Detail */
            error_detail: string | null;
            /** Failed Count */
            failed_count: number;
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /**
             * Logical Date
             * Format: date
             */
            logical_date: string;
            /** Normalized Count */
            normalized_count: number;
            operation: components["schemas"]["RunOperation"];
            /** Schema Version */
            schema_version: number;
            /**
             * Started At
             * Format: date-time
             */
            started_at: string;
            status: components["schemas"]["RunStatus"];
            /**
             * Topic Id
             * Format: uuid
             */
            topic_id: string;
        };
        /** SourceIdentityResponse */
        SourceIdentityResponse: {
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /** External Id */
            external_id: string;
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /**
             * Paper Id
             * Format: uuid
             */
            paper_id: string;
            /**
             * Paper Version Id
             * Format: uuid
             */
            paper_version_id: string;
            /** Schema Version */
            schema_version: number;
            /**
             * Source
             * @constant
             */
            source: "arxiv";
            /** Source Url */
            source_url: string;
            /** Source Version */
            source_version: string;
        };
        /** TopicListResponse */
        TopicListResponse: {
            /** Items */
            items: components["schemas"]["TopicSummary"][];
            /** Total */
            total: number;
        };
        /** TopicSummary */
        TopicSummary: {
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /** Description */
            description: string;
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Name */
            name: string;
            /** Schema Version */
            schema_version: number;
            /** Slug */
            slug: string;
        };
        /** ValidationError */
        ValidationError: {
            /** Context */
            ctx?: Record<string, never>;
            /** Input */
            input?: unknown;
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    listPapers: {
        parameters: {
            query?: {
                topic?: string | null;
                limit?: number;
                offset?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PaperListResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    getPaper: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                paper_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PaperDetailResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    listRuns: {
        parameters: {
            query?: {
                topic?: string | null;
                limit?: number;
                offset?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RunListResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    getLatestRun: {
        parameters: {
            query?: {
                topic?: string | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RunDetailResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    listTopics: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TopicListResponse"];
                };
            };
        };
    };
    getLiveness: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["LiveResponse"];
                };
            };
        };
    };
    getReadiness: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ReadyResponse"];
                };
            };
            /** @description Database unavailable or migration incompatible */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
}
