/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/v1/papers": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Papers */
        get: operations["listPapers"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/papers/{paper_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Paper */
        get: operations["getPaper"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/papers/{paper_id}/analysis": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Paper Analysis */
        get: operations["getPaperAnalysis"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/papers/{paper_id}/evidence": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Paper Evidence */
        get: operations["listPaperEvidence"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/runs": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Runs */
        get: operations["listRuns"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/runs/latest": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Latest Run */
        get: operations["getLatestRun"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/topics": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Topics */
        get: operations["listTopics"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/health/live": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Liveness */
        get: operations["getLiveness"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/health/ready": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Readiness */
        get: operations["getReadiness"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** AnalysisClaimResponse */
        AnalysisClaimResponse: {
            /**
             * Analysis Id
             * Format: uuid
             */
            analysis_id: string;
            claim_type: components["schemas"]["ClaimType"];
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /**
             * Generated At
             * Format: date-time
             */
            generated_at: string;
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Key */
            key: string;
            /** Model Version */
            model_version: string;
            /**
             * Paper Id
             * Format: uuid
             */
            paper_id: string;
            /**
             * Paper Version Id
             * Format: uuid
             */
            paper_version_id: string;
            /** Prompt Version */
            prompt_version: string;
            /** Provider */
            provider: string;
            /** Schema Version */
            schema_version: number;
            /** Source */
            source: string;
            /** Text */
            text: string;
            verification_status: components["schemas"]["VerificationStatus"];
        };
        /**
         * AnalysisScope
         * @enum {string}
         */
        AnalysisScope: "ABSTRACT_ONLY" | "FULL_TEXT";
        /** ApiErrorDetail */
        ApiErrorDetail: {
            /** Code */
            code: string;
            /** Message */
            message: string;
        };
        /** ApiErrorResponse */
        ApiErrorResponse: {
            detail: components["schemas"]["ApiErrorDetail"];
        };
        /**
         * ClaimType
         * @enum {string}
         */
        ClaimType: "RESEARCH_PROBLEM" | "METHOD" | "CONTRIBUTION" | "RESULT" | "LIMITATION";
        /** EvidenceListResponse */
        EvidenceListResponse: {
            /** Items */
            items: components["schemas"]["EvidenceResponse"][];
            /** Total */
            total: number;
        };
        /** EvidenceResponse */
        EvidenceResponse: {
            /**
             * Analysis Id
             * Format: uuid
             */
            analysis_id: string;
            /** Coordinates */
            coordinates: components["schemas"]["PageCoordinatesResponse"][];
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            evidence_type: components["schemas"]["EvidenceType"];
            /** Excerpt */
            excerpt: string;
            /** Extraction Source */
            extraction_source: string;
            /**
             * Generated At
             * Format: date-time
             */
            generated_at: string;
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Key */
            key: string;
            /** Model Version */
            model_version: string;
            /**
             * Paper Id
             * Format: uuid
             */
            paper_id: string;
            /**
             * Paper Version Id
             * Format: uuid
             */
            paper_version_id: string;
            /** Passage Id */
            passage_id: string;
            /** Prompt Version */
            prompt_version: string;
            /** Provider */
            provider: string;
            /** Schema Version */
            schema_version: number;
            /** Section */
            section: string;
            /** Supported Claim Ids */
            supported_claim_ids: string[];
            verification_status: components["schemas"]["VerificationStatus"];
        };
        /**
         * EvidenceType
         * @enum {string}
         */
        EvidenceType: "SUPPORTS" | "QUALIFIES" | "CONTRADICTS";
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /** LiveResponse */
        LiveResponse: {
            /**
             * Status
             * @default alive
             * @constant
             */
            status: "alive";
        };
        /** ModelUsageResponse */
        ModelUsageResponse: {
            /** Call Count */
            call_count: number;
            /** Completion Tokens */
            completion_tokens: number;
            /** Duration Ms */
            duration_ms: number;
            /** Estimated Cost Usd */
            estimated_cost_usd: string | null;
            /** Prompt Tokens */
            prompt_tokens: number;
            /** Total Tokens */
            total_tokens: number;
        };
        /** PageCoordinatesResponse */
        PageCoordinatesResponse: {
            /** Height */
            height: number;
            /** Page */
            page: number;
            /** Width */
            width: number;
            /** X */
            x: number;
            /** Y */
            y: number;
        };
        /** PaperAnalysisResponse */
        PaperAnalysisResponse: {
            analysis_scope: components["schemas"]["AnalysisScope"];
            /** Arxiv Version */
            arxiv_version: number;
            /** Claims */
            claims: components["schemas"]["AnalysisClaimResponse"][];
            /** Configured Model */
            configured_model: string;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /**
             * Generated At
             * Format: date-time
             */
            generated_at: string;
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Key Contributions */
            key_contributions: string[];
            /** Limitations */
            limitations: string[];
            /** Method Summary */
            method_summary: string;
            /** Model Version */
            model_version: string;
            /**
             * Paper Id
             * Format: uuid
             */
            paper_id: string;
            /**
             * Paper Version Id
             * Format: uuid
             */
            paper_version_id: string;
            /** Parsed Paper Id */
            parsed_paper_id: string | null;
            /** Parser Name */
            parser_name: string | null;
            /** Parser Version */
            parser_version: string | null;
            /** Prompt Version */
            prompt_version: string;
            /** Provider */
            provider: string;
            /** Research Problem */
            research_problem: string;
            /** Schema Version */
            schema_version: number;
            /** Source */
            source: string;
            /** Summary */
            summary: string;
            usage: components["schemas"]["ModelUsageResponse"];
            verification_status: components["schemas"]["VerificationStatus"];
        };
        /** PaperDetailResponse */
        PaperDetailResponse: {
            /** Abstract */
            abstract: string;
            /** Authors */
            authors: string[];
            /** Canonical Arxiv Id */
            canonical_arxiv_id: string;
            /** Categories */
            categories: string[];
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /** Current Version */
            current_version: number;
            /**
             * First Submitted At
             * Format: date-time
             */
            first_submitted_at: string;
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /**
             * Latest Updated At
             * Format: date-time
             */
            latest_updated_at: string;
            /** Pdf Url */
            pdf_url: string;
            /** Primary Category */
            primary_category: string;
            /** Schema Version */
            schema_version: number;
            /** Source Identities */
            source_identities: components["schemas"]["SourceIdentityResponse"][];
            /** Title */
            title: string;
            /** Topic Slugs */
            topic_slugs: string[];
            /** Versions */
            versions: components["schemas"]["PaperVersionResponse"][];
        };
        /** PaperListResponse */
        PaperListResponse: {
            /** Items */
            items: components["schemas"]["PaperSummary"][];
            /** Limit */
            limit: number;
            /** Offset */
            offset: number;
            /** Total */
            total: number;
        };
        /**
         * PaperStage
         * @enum {string}
         */
        PaperStage: "DISCOVERED" | "NORMALIZED" | "ENRICHED" | "RELEVANCE_SCORED" | "SELECTED" | "PDF_DOWNLOADED" | "PARSED" | "ANALYZED" | "EVIDENCE_EXTRACTED" | "PRIOR_WORK_RETRIEVED" | "COMPARED" | "GRAPH_UPDATED" | "PUBLISHED";
        /** PaperSummary */
        PaperSummary: {
            /** Abstract */
            abstract: string;
            /** Authors */
            authors: string[];
            /** Canonical Arxiv Id */
            canonical_arxiv_id: string;
            /** Categories */
            categories: string[];
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /** Current Version */
            current_version: number;
            /**
             * First Submitted At
             * Format: date-time
             */
            first_submitted_at: string;
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /**
             * Latest Updated At
             * Format: date-time
             */
            latest_updated_at: string;
            /** Pdf Url */
            pdf_url: string;
            /** Primary Category */
            primary_category: string;
            /** Schema Version */
            schema_version: number;
            /** Title */
            title: string;
        };
        /** PaperVersionResponse */
        PaperVersionResponse: {
            /** Abstract */
            abstract: string;
            /** Authors */
            authors: string[];
            /** Canonical Arxiv Id */
            canonical_arxiv_id: string;
            /** Categories */
            categories: string[];
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /**
             * Paper Id
             * Format: uuid
             */
            paper_id: string;
            /** Pdf Url */
            pdf_url: string;
            /** Primary Category */
            primary_category: string;
            /** Schema Version */
            schema_version: number;
            /** Source Url */
            source_url: string;
            /**
             * Submitted At
             * Format: date-time
             */
            submitted_at: string;
            /** Title */
            title: string;
            /**
             * Updated At
             * Format: date-time
             */
            updated_at: string;
            /** Version */
            version: number;
        };
        /** ReadyResponse */
        ReadyResponse: {
            /**
             * Database
             * @default ready
             * @constant
             */
            database: "ready";
            /**
             * Migrations
             * @default current
             * @constant
             */
            migrations: "current";
            /**
             * Status
             * @default ready
             * @constant
             */
            status: "ready";
        };
        /** ReportFailureResponse */
        ReportFailureResponse: {
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /** Error Code */
            error_code: string;
            /** Error Detail */
            error_detail: string;
            failed_stage: components["schemas"]["PaperStage"];
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /**
             * Paper Id
             * Format: uuid
             */
            paper_id: string;
            /**
             * Paper Version Id
             * Format: uuid
             */
            paper_version_id: string;
            /**
             * Report Id
             * Format: uuid
             */
            report_id: string;
            /** Retryable */
            retryable: boolean;
            /** Schema Version */
            schema_version: number;
        };
        /** ReportResponse */
        ReportResponse: {
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /** Failures */
            failures: components["schemas"]["ReportFailureResponse"][];
            /**
             * Generated At
             * Format: date-time
             */
            generated_at: string;
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /**
             * Logical Date
             * Format: date
             */
            logical_date: string;
            /**
             * Run Id
             * Format: uuid
             */
            run_id: string;
            /** Schema Version */
            schema_version: number;
            /** Source */
            source: string;
            status: components["schemas"]["RunStatus"];
            /** Summary */
            summary: string;
            /** Title */
            title: string;
            /**
             * Topic Id
             * Format: uuid
             */
            topic_id: string;
        };
        /** RunDetailResponse */
        RunDetailResponse: {
            analysis_scope: components["schemas"]["AnalysisScope"] | null;
            /** Completed At */
            completed_at: string | null;
            /** Completed Count */
            completed_count: number;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /** Cursor From */
            cursor_from: string | null;
            /** Cursor To */
            cursor_to: string | null;
            /** Discovered Count */
            discovered_count: number;
            /** Error Code */
            error_code: string | null;
            /** Error Detail */
            error_detail: string | null;
            /** Failed Count */
            failed_count: number;
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Items */
            items: components["schemas"]["RunItemResponse"][];
            /**
             * Logical Date
             * Format: date
             */
            logical_date: string;
            /** Normalized Count */
            normalized_count: number;
            operation: components["schemas"]["RunOperation"];
            report: components["schemas"]["ReportResponse"] | null;
            /** Schema Version */
            schema_version: number;
            /** Selected Count */
            selected_count: number;
            /**
             * Started At
             * Format: date-time
             */
            started_at: string;
            status: components["schemas"]["RunStatus"];
            /**
             * Topic Id
             * Format: uuid
             */
            topic_id: string;
        };
        /** RunItemResponse */
        RunItemResponse: {
            /** Canonical Arxiv Id */
            canonical_arxiv_id: string;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /** Error Code */
            error_code: string | null;
            /** Error Detail */
            error_detail: string | null;
            failed_stage: components["schemas"]["PaperStage"] | null;
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /**
             * Paper Id
             * Format: uuid
             */
            paper_id: string;
            /** Paper Title */
            paper_title: string;
            /**
             * Paper Version Id
             * Format: uuid
             */
            paper_version_id: string;
            /** Retryable */
            retryable: boolean | null;
            /**
             * Run Id
             * Format: uuid
             */
            run_id: string;
            /** Schema Version */
            schema_version: number;
            stage: components["schemas"]["PaperStage"];
            status: components["schemas"]["RunItemStatus"];
            /**
             * Updated At
             * Format: date-time
             */
            updated_at: string;
        };
        /**
         * RunItemStatus
         * @enum {string}
         */
        RunItemStatus: "IN_PROGRESS" | "COMPLETED" | "FAILED";
        /** RunListResponse */
        RunListResponse: {
            /** Items */
            items: components["schemas"]["RunSummary"][];
            /** Limit */
            limit: number;
            /** Offset */
            offset: number;
            /** Total */
            total: number;
        };
        /**
         * RunOperation
         * @enum {string}
         */
        RunOperation: "ARXIV_INGESTION" | "STRUCTURED_ANALYSIS";
        /**
         * RunStatus
         * @enum {string}
         */
        RunStatus: "RUNNING" | "COMPLETE" | "PARTIAL" | "FAILED";
        /** RunSummary */
        RunSummary: {
            analysis_scope: components["schemas"]["AnalysisScope"] | null;
            /** Completed At */
            completed_at: string | null;
            /** Completed Count */
            completed_count: number;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /** Cursor From */
            cursor_from: string | null;
            /** Cursor To */
            cursor_to: string | null;
            /** Discovered Count */
            discovered_count: number;
            /** Error Code */
            error_code: string | null;
            /** Error Detail */
            error_detail: string | null;
            /** Failed Count */
            failed_count: number;
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /**
             * Logical Date
             * Format: date
             */
            logical_date: string;
            /** Normalized Count */
            normalized_count: number;
            operation: components["schemas"]["RunOperation"];
            /** Schema Version */
            schema_version: number;
            /** Selected Count */
            selected_count: number;
            /**
             * Started At
             * Format: date-time
             */
            started_at: string;
            status: components["schemas"]["RunStatus"];
            /**
             * Topic Id
             * Format: uuid
             */
            topic_id: string;
        };
        /** SourceIdentityResponse */
        SourceIdentityResponse: {
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /** External Id */
            external_id: string;
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /**
             * Paper Id
             * Format: uuid
             */
            paper_id: string;
            /**
             * Paper Version Id
             * Format: uuid
             */
            paper_version_id: string;
            /** Schema Version */
            schema_version: number;
            /**
             * Source
             * @constant
             */
            source: "arxiv";
            /** Source Url */
            source_url: string;
            /** Source Version */
            source_version: string;
        };
        /** TopicListResponse */
        TopicListResponse: {
            /** Items */
            items: components["schemas"]["TopicSummary"][];
            /** Total */
            total: number;
        };
        /** TopicSummary */
        TopicSummary: {
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /** Description */
            description: string;
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Name */
            name: string;
            /** Schema Version */
            schema_version: number;
            /** Slug */
            slug: string;
        };
        /** ValidationError */
        ValidationError: {
            /** Context */
            ctx?: Record<string, never>;
            /** Input */
            input?: unknown;
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
        };
        /**
         * VerificationStatus
         * @enum {string}
         */
        VerificationStatus: "UNVERIFIED" | "HUMAN_VERIFIED" | "REJECTED";
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    listPapers: {
        parameters: {
            query?: {
                topic?: string | null;
                limit?: number;
                offset?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PaperListResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    getPaper: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                paper_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PaperDetailResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    getPaperAnalysis: {
        parameters: {
            query?: {
                paper_version_id?: string | null;
                scope?: components["schemas"]["AnalysisScope"] | null;
            };
            header?: never;
            path: {
                paper_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PaperAnalysisResponse"];
                };
            };
            /** @description Paper or analysis not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiErrorResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
            /** @description Analysis storage unavailable */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiErrorResponse"];
                };
            };
        };
    };
    listPaperEvidence: {
        parameters: {
            query: {
                analysis_id: string;
                paper_version_id?: string | null;
                scope?: components["schemas"]["AnalysisScope"] | null;
            };
            header?: never;
            path: {
                paper_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EvidenceListResponse"];
                };
            };
            /** @description Paper or analysis not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiErrorResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
            /** @description Evidence storage unavailable */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiErrorResponse"];
                };
            };
        };
    };
    listRuns: {
        parameters: {
            query?: {
                topic?: string | null;
                limit?: number;
                offset?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RunListResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    getLatestRun: {
        parameters: {
            query?: {
                topic?: string | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RunDetailResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    listTopics: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TopicListResponse"];
                };
            };
        };
    };
    getLiveness: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["LiveResponse"];
                };
            };
        };
    };
    getReadiness: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ReadyResponse"];
                };
            };
            /** @description Database unavailable or migration incompatible */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
}
